# render.yaml
services:
  - type: web
    name: atrio-backend
    env: node
    plan: free
    buildCommand: npm install && npx prisma generate
    startCommand: npm run start:prod
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: NODE_ENV
        value: production
      - key: ADMIN_PASSWORD
        sync: false
      - key: MEMBER_PASSWORD
        sync: false
